/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yeoupooh' at '1/24/16 11:30 AM' with Gradle 2.10
 *
 * @author yeoupooh, @date 1/24/16 11:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
